version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: urlshortener-db
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: urluser
      POSTGRES_PASSWORD: urlpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: urlshortener-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: urluser
      SPRING_DATASOURCE_PASSWORD: urlpass
    restart: always

volumes:
  pgdata:
