spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: urluser
    password: urlpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
